// Generated by gencpp from file skeleton/festTTS.msg
// DO NOT EDIT!


#ifndef SKELETON_MESSAGE_FESTTTS_H
#define SKELETON_MESSAGE_FESTTTS_H

#include <ros/service_traits.h>


#include <skeleton/festTTSRequest.h>
#include <skeleton/festTTSResponse.h>


namespace skeleton
{

struct festTTS
{

typedef festTTSRequest Request;
typedef festTTSResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct festTTS
} // namespace skeleton


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::skeleton::festTTS > {
  static const char* value()
  {
    return "671f8e4998eaec79f1c47e339dfd527b";
  }

  static const char* value(const ::skeleton::festTTS&) { return value(); }
};

template<>
struct DataType< ::skeleton::festTTS > {
  static const char* value()
  {
    return "skeleton/festTTS";
  }

  static const char* value(const ::skeleton::festTTS&) { return value(); }
};


// service_traits::MD5Sum< ::skeleton::festTTSRequest> should match 
// service_traits::MD5Sum< ::skeleton::festTTS > 
template<>
struct MD5Sum< ::skeleton::festTTSRequest>
{
  static const char* value()
  {
    return MD5Sum< ::skeleton::festTTS >::value();
  }
  static const char* value(const ::skeleton::festTTSRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::skeleton::festTTSRequest> should match 
// service_traits::DataType< ::skeleton::festTTS > 
template<>
struct DataType< ::skeleton::festTTSRequest>
{
  static const char* value()
  {
    return DataType< ::skeleton::festTTS >::value();
  }
  static const char* value(const ::skeleton::festTTSRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::skeleton::festTTSResponse> should match 
// service_traits::MD5Sum< ::skeleton::festTTS > 
template<>
struct MD5Sum< ::skeleton::festTTSResponse>
{
  static const char* value()
  {
    return MD5Sum< ::skeleton::festTTS >::value();
  }
  static const char* value(const ::skeleton::festTTSResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::skeleton::festTTSResponse> should match 
// service_traits::DataType< ::skeleton::festTTS > 
template<>
struct DataType< ::skeleton::festTTSResponse>
{
  static const char* value()
  {
    return DataType< ::skeleton::festTTS >::value();
  }
  static const char* value(const ::skeleton::festTTSResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SKELETON_MESSAGE_FESTTTS_H
