// Generated by gencpp from file weather/responseRequest.msg
// DO NOT EDIT!


#ifndef WEATHER_MESSAGE_RESPONSEREQUEST_H
#define WEATHER_MESSAGE_RESPONSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace weather
{
template <class ContainerAllocator>
struct responseRequest_
{
  typedef responseRequest_<ContainerAllocator> Type;

  responseRequest_()
    : city()  {
    }
  responseRequest_(const ContainerAllocator& _alloc)
    : city(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _city_type;
  _city_type city;




  typedef boost::shared_ptr< ::weather::responseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::weather::responseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct responseRequest_

typedef ::weather::responseRequest_<std::allocator<void> > responseRequest;

typedef boost::shared_ptr< ::weather::responseRequest > responseRequestPtr;
typedef boost::shared_ptr< ::weather::responseRequest const> responseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::weather::responseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::weather::responseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace weather

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'weather': ['/home/alex/catkin_ws/src/weather/msg', '/home/alex/catkin_ws/src/weather/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::weather::responseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::weather::responseRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::weather::responseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::weather::responseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weather::responseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::weather::responseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::weather::responseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ca7c9808e023a3417491b7104889ca1";
  }

  static const char* value(const ::weather::responseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ca7c9808e023a34ULL;
  static const uint64_t static_value2 = 0x17491b7104889ca1ULL;
};

template<class ContainerAllocator>
struct DataType< ::weather::responseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "weather/responseRequest";
  }

  static const char* value(const ::weather::responseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::weather::responseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string city\n\
";
  }

  static const char* value(const ::weather::responseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::weather::responseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.city);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct responseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::weather::responseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::weather::responseRequest_<ContainerAllocator>& v)
  {
    s << indent << "city: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.city);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEATHER_MESSAGE_RESPONSEREQUEST_H
