uint8 rightMotorSpeed
bool rightMotorSpeedCommand
uint8 leftMotorSpeed
bool leftMotorSpeedCommand
int16 cameraTilt
bool cameraTiltCommand
int16 cameraPan
bool cameraPanCommand
uint8 digital1
bool digital1Command
uint8 digital2
bool digital2Command
---
bool commandSuccessful
