// Generated by gencpp from file DLIB/DLIB.msg
// DO NOT EDIT!


#ifndef DLIB_MESSAGE_DLIB_H
#define DLIB_MESSAGE_DLIB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace DLIB
{
template <class ContainerAllocator>
struct DLIB_
{
  typedef DLIB_<ContainerAllocator> Type;

  DLIB_()
    : id(0)
    , data()  {
    }
  DLIB_(const ContainerAllocator& _alloc)
    : id(0)
    , data(_alloc)  {
    }



   typedef int8_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;




  typedef boost::shared_ptr< ::DLIB::DLIB_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::DLIB::DLIB_<ContainerAllocator> const> ConstPtr;

}; // struct DLIB_

typedef ::DLIB::DLIB_<std::allocator<void> > DLIB;

typedef boost::shared_ptr< ::DLIB::DLIB > DLIBPtr;
typedef boost::shared_ptr< ::DLIB::DLIB const> DLIBConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::DLIB::DLIB_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::DLIB::DLIB_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace DLIB

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'DLIB': ['/home/julian/sandbox/jpham18/ROS/catkin_ws/src/DLIB/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::DLIB::DLIB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DLIB::DLIB_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DLIB::DLIB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DLIB::DLIB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DLIB::DLIB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DLIB::DLIB_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::DLIB::DLIB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3398c77d30999b784ef30c252c7c0e98";
  }

  static const char* value(const ::DLIB::DLIB_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3398c77d30999b78ULL;
  static const uint64_t static_value2 = 0x4ef30c252c7c0e98ULL;
};

template<class ContainerAllocator>
struct DataType< ::DLIB::DLIB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DLIB/DLIB";
  }

  static const char* value(const ::DLIB::DLIB_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::DLIB::DLIB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 id\n\
string data\n\
";
  }

  static const char* value(const ::DLIB::DLIB_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::DLIB::DLIB_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DLIB_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::DLIB::DLIB_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::DLIB::DLIB_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.id);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DLIB_MESSAGE_DLIB_H
