// Generated by gencpp from file DLIB/UnknownFace.msg
// DO NOT EDIT!


#ifndef DLIB_MESSAGE_UNKNOWNFACE_H
#define DLIB_MESSAGE_UNKNOWNFACE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace DLIB
{
template <class ContainerAllocator>
struct UnknownFace_
{
  typedef UnknownFace_<ContainerAllocator> Type;

  UnknownFace_()
    : name()
    , llx(0)
    , lly(0)
    , urx(0)
    , ury(0)  {
    }
  UnknownFace_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , llx(0)
    , lly(0)
    , urx(0)
    , ury(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef uint8_t _llx_type;
  _llx_type llx;

   typedef uint8_t _lly_type;
  _lly_type lly;

   typedef uint8_t _urx_type;
  _urx_type urx;

   typedef uint8_t _ury_type;
  _ury_type ury;




  typedef boost::shared_ptr< ::DLIB::UnknownFace_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::DLIB::UnknownFace_<ContainerAllocator> const> ConstPtr;

}; // struct UnknownFace_

typedef ::DLIB::UnknownFace_<std::allocator<void> > UnknownFace;

typedef boost::shared_ptr< ::DLIB::UnknownFace > UnknownFacePtr;
typedef boost::shared_ptr< ::DLIB::UnknownFace const> UnknownFaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::DLIB::UnknownFace_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::DLIB::UnknownFace_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace DLIB

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'DLIB': ['/home/julian/sandbox/jpham18/ROS/catkin_ws/src/DLIB/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::DLIB::UnknownFace_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::DLIB::UnknownFace_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DLIB::UnknownFace_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::DLIB::UnknownFace_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DLIB::UnknownFace_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::DLIB::UnknownFace_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::DLIB::UnknownFace_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cad868307b5c8d4a7455516e9791b3a";
  }

  static const char* value(const ::DLIB::UnknownFace_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cad868307b5c8d4ULL;
  static const uint64_t static_value2 = 0xa7455516e9791b3aULL;
};

template<class ContainerAllocator>
struct DataType< ::DLIB::UnknownFace_<ContainerAllocator> >
{
  static const char* value()
  {
    return "DLIB/UnknownFace";
  }

  static const char* value(const ::DLIB::UnknownFace_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::DLIB::UnknownFace_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
uint8 llx\n\
uint8 lly\n\
uint8 urx\n\
uint8 ury\n\
";
  }

  static const char* value(const ::DLIB::UnknownFace_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::DLIB::UnknownFace_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.llx);
      stream.next(m.lly);
      stream.next(m.urx);
      stream.next(m.ury);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct UnknownFace_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::DLIB::UnknownFace_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::DLIB::UnknownFace_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "llx: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.llx);
    s << indent << "lly: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.lly);
    s << indent << "urx: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.urx);
    s << indent << "ury: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ury);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DLIB_MESSAGE_UNKNOWNFACE_H
