// Generated by gencpp from file music/musicgenreResponse.msg
// DO NOT EDIT!


#ifndef MUSIC_MESSAGE_MUSICGENRERESPONSE_H
#define MUSIC_MESSAGE_MUSICGENRERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace music
{
template <class ContainerAllocator>
struct musicgenreResponse_
{
  typedef musicgenreResponse_<ContainerAllocator> Type;

  musicgenreResponse_()
    : song()  {
    }
  musicgenreResponse_(const ContainerAllocator& _alloc)
    : song(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _song_type;
  _song_type song;




  typedef boost::shared_ptr< ::music::musicgenreResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::music::musicgenreResponse_<ContainerAllocator> const> ConstPtr;

}; // struct musicgenreResponse_

typedef ::music::musicgenreResponse_<std::allocator<void> > musicgenreResponse;

typedef boost::shared_ptr< ::music::musicgenreResponse > musicgenreResponsePtr;
typedef boost::shared_ptr< ::music::musicgenreResponse const> musicgenreResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::music::musicgenreResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::music::musicgenreResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace music

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'music': ['/home/alex/catkin_ws/src/music/msg', '/home/alex/catkin_ws/src/music/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::music::musicgenreResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::music::musicgenreResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::music::musicgenreResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::music::musicgenreResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::music::musicgenreResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::music::musicgenreResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::music::musicgenreResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8096b89c5f87044e3056ef7794163714";
  }

  static const char* value(const ::music::musicgenreResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8096b89c5f87044eULL;
  static const uint64_t static_value2 = 0x3056ef7794163714ULL;
};

template<class ContainerAllocator>
struct DataType< ::music::musicgenreResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "music/musicgenreResponse";
  }

  static const char* value(const ::music::musicgenreResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::music::musicgenreResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string song\n\
\n\
";
  }

  static const char* value(const ::music::musicgenreResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::music::musicgenreResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.song);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct musicgenreResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::music::musicgenreResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::music::musicgenreResponse_<ContainerAllocator>& v)
  {
    s << indent << "song: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.song);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MUSIC_MESSAGE_MUSICGENRERESPONSE_H
