#!/usr/bin/env python

def callback(self,data):
    text=str(data)
    text2 = WhitespaceTokenizer().tokenize(text)
    text2.remove("data:")
    print(text2)
    if data==1:
        while True:
            try:
               Nora.test(self)
            except rospy.ROSInterruptException:
                pass
            

def listener(self):
    rospy.init_node('Speech',anonymous=True) 
    rospy.Subscriber("strtspch",String,callback)
    rospy.spin()

if __name__=='__main__':
    listener() 