// Generated by gencpp from file skeleton/Face.msg
// DO NOT EDIT!


#ifndef SKELETON_MESSAGE_FACE_H
#define SKELETON_MESSAGE_FACE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace skeleton
{
template <class ContainerAllocator>
struct Face_
{
  typedef Face_<ContainerAllocator> Type;

  Face_()
    : name()
    , image()
    , llx(0)
    , lly(0)
    , urx(0)
    , ury(0)  {
    }
  Face_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , image(_alloc)
    , llx(0)
    , lly(0)
    , urx(0)
    , ury(0)  {
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _image_type;
  _image_type image;

   typedef uint32_t _llx_type;
  _llx_type llx;

   typedef uint32_t _lly_type;
  _lly_type lly;

   typedef uint32_t _urx_type;
  _urx_type urx;

   typedef uint32_t _ury_type;
  _ury_type ury;




  typedef boost::shared_ptr< ::skeleton::Face_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::skeleton::Face_<ContainerAllocator> const> ConstPtr;

}; // struct Face_

typedef ::skeleton::Face_<std::allocator<void> > Face;

typedef boost::shared_ptr< ::skeleton::Face > FacePtr;
typedef boost::shared_ptr< ::skeleton::Face const> FaceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::skeleton::Face_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::skeleton::Face_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace skeleton

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'skeleton': ['/home/aurash/catkin_ws/src/skeleton/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::skeleton::Face_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::skeleton::Face_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skeleton::Face_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::skeleton::Face_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skeleton::Face_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::skeleton::Face_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::skeleton::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d177734d9fba9e1fbead9ccf8016ee6";
  }

  static const char* value(const ::skeleton::Face_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d177734d9fba9e1ULL;
  static const uint64_t static_value2 = 0xfbead9ccf8016ee6ULL;
};

template<class ContainerAllocator>
struct DataType< ::skeleton::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "skeleton/Face";
  }

  static const char* value(const ::skeleton::Face_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::skeleton::Face_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string image\n\
uint32 llx\n\
uint32 lly\n\
uint32 urx\n\
uint32 ury\n\
\n\
";
  }

  static const char* value(const ::skeleton::Face_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::skeleton::Face_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.image);
      stream.next(m.llx);
      stream.next(m.lly);
      stream.next(m.urx);
      stream.next(m.ury);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Face_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::skeleton::Face_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::skeleton::Face_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "image: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.image);
    s << indent << "llx: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.llx);
    s << indent << "lly: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.lly);
    s << indent << "urx: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.urx);
    s << indent << "ury: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ury);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SKELETON_MESSAGE_FACE_H
